[package]
name = "winit-ohos"
version = "0.31.0-beta.2"
edition = "2024"
rust-version = "1.88"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ohos-rs/winit-ohos.git"
description = "Winit's OpenHarmony backend"

[features]
default = []
plugin-window = ["dep:openharmony-ability-plugin-window"]

[dependencies]
winit-core = { version = "=0.31.0-beta.2", git = "https://github.com/richerfu/winit.git", branch = "master" }
tracing = { version = "0.1.40", default-features = false }
dpi = { version = "=0.1.2", git = "https://github.com/richerfu/winit.git", branch = "master" }
rwh_06 = { package = "raw-window-handle", version = "0.6", features = ["std"] }

openharmony-ability = { version = "1.0.0-beta.1" }
openharmony-ability-derive = { version = "1.0.0-beta.1" }
openharmony-ability-plugin-window = { version = "1.0.0-beta.1", optional = true }
